export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_MATCHES = "GET_MATCHES";
export const MATCHES_LOADING = "MATCHES_LOADING";